spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:9000/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Friendly routes
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=room-service
spring.cloud.gateway.routes[1].uri=lb://room-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/rooms/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=booking-service
spring.cloud.gateway.routes[2].uri=lb://booking-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/bookings/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

management.endpoints.web.exposure.include=health,info
